// <auto-generated />
using IELTSWord.Migrations.Startup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IELTSWord.Migrations.Startup.Migrations
{
    [DbContext(typeof(KVContext))]
    partial class KVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3");

            modelBuilder.Entity("IELTSWord.Migrations.Startup.KV", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
